// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LaunchAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LaunchAgent'](arg1, arg2, arg3, arg4);
}

export function LaunchBatch(arg1, arg2) {
  return window['go']['main']['App']['LaunchBatch'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function SendCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendCommand'](arg1, arg2, arg3);
}

export function StopAgent(arg1) {
  return window['go']['main']['App']['StopAgent'](arg1);
}

export function SubmitInput(arg1, arg2) {
  return window['go']['main']['App']['SubmitInput'](arg1, arg2);
}

export function SubmitWithFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SubmitWithFiles'](arg1, arg2, arg3, arg4);
}
