// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runner} from '../models';

export function LaunchAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function LaunchBatch(arg1:number,arg2:string):Promise<void>;

export function ListAgents():Promise<Array<runner.AgentInfo>>;

export function SendCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopAgent(arg1:string):Promise<void>;

export function SubmitInput(arg1:string,arg2:string):Promise<void>;

export function SubmitWithFiles(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<void>;
